// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_new_app.Model;

#nullable disable

namespace my_new_app.Migrations;

[DbContext(typeof(UserDataContext))]
partial class UserDataContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.12");
        modelBuilder.Entity("my_new_app.Model.TaskGroup", b =>
        {
            b.Property<int>("TaskGroupId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.HasKey("TaskGroupId");
            b.ToTable("TaskGroups");
        });
        modelBuilder.Entity("my_new_app.Model.UserTask", b =>
        {
            b.Property<int>("UserTaskId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("Deadline").HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<int?>("TaskGroupId").HasColumnType("INTEGER");
            b.Property<int>("UserId").HasColumnType("INTEGER");
            b.HasKey("UserTaskId");
            b.HasIndex("TaskGroupId");
            b.HasIndex("UserId");
            b.ToTable("UserTasks");
        });
        modelBuilder.Entity("my_new_app.Model.User", b =>
        {
            b.Property<int>("UserId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.HasKey("UserId");
            b.ToTable("Users");
        });
        modelBuilder.Entity("my_new_app.Model.UserTask", b =>
        {
            b.HasOne("my_new_app.Model.TaskGroup", "TaskGroup").WithMany("UserTasks").HasForeignKey("TaskGroupId").OnDelete(DeleteBehavior.SetNull);
            b.HasOne("my_new_app.Model.User", "User").WithMany("UserTasks").HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict);
            b.Navigation("TaskGroup");
            b.Navigation("User");
        });
        modelBuilder.Entity("my_new_app.Model.TaskGroup", b => b.Navigation("UserTasks"));
        modelBuilder.Entity("my_new_app.Model.User", b => b.Navigation("UserTasks"));
    }
}
